/* Aides publiques : synthèse du maître 06 et de l'aide Interludes de GPT vision. */
(()=>{'use strict';
const guides=[
['Interludes','Préparer une activité entre deux aventures','Annoncez un objectif, le temps souhaité, le lieu ou le contact, les moyens et le budget. Le MJ confirme le temps réellement disponible et le résultat. Une activité ordinaire, accessible et financée ne demande pas systématiquement de jet. Une rareté, une opposition ou un délai peuvent créer une incertitude.','notes'],
['Progression','Apprendre et préparer un passage de Cercle','Utilisez Progression pour préparer talents, compétences et attributs, puis vérifier les coûts et conditions. Chercher un mentor peut faire l’objet d’un interlude. Le passage de Cercle reste un événement joué : une préparation ne le valide pas automatiquement.','progression'],
['Commerce','Acheter ou vendre sans double déclaration','Consultez les disponibilités du marché, puis transmettez votre proposition dans Biens & services. Une proposition ne modifie pas à elle seule l’argent ou l’inventaire. Attendez la validation du MJ. Inutile de recopier le même achat dans un interlude ; vous pouvez y ajouter la recherche d’un artisan ou une négociation particulière.','market'],
['Équipement','Transporter, soulever et s’encombrer','La capacité de transport indique le poids porté sans malus. La capacité à soulever est distincte : elle ne permet pas de marcher avec cette charge. Au-delà du transport, la Dextérité diminue de l’écart entre la Force minimale nécessaire et la Force réelle. Exemple : FOR 13 = 55 kg à transporter et 110 kg à soulever. Le calculateur du marché permet de préparer une charge.','gear'],
['Règles de table','Bonus, blessures et récupération','Un modificateur numérique de test modifie le niveau avant le lancer, avec un minimum de 1. Les dés de Karma s’ajoutent séparément. La première Blessure grave ne pénalise pas les tests d’action ; chaque suivante impose −1 niveau. Pour un test de récupération, chaque Blessure grave impose −1 niveau.','combat'],
['Interludes','Choisir son train de vie','Modeste : économies et confort limité. Convenable : conditions ordinaires. Confortable : bon repos et dépenses visibles. Fastueux : prestige et accès à certains milieux, mais aussi attention accrue. Ces choix ont des conséquences économiques et sociales, sans pénalité automatique sur les talents. Indiquez votre choix et votre budget dans la demande.','notes'],
['Magie et groupe','Rechercher un objet ou développer les liens du groupe','Un interlude peut servir à retrouver un Nom, un témoin, une archive ou une légende. Un objet Nommé n’est pas automatiquement magique ou à filament. Une recherche ne révèle pas automatiquement une connaissance-clef et ne dépense pas de PL à elle seule. Les liens du groupe se développent dans le récit ; aucun avantage avancé de trame de groupe n’est accordé automatiquement.','notes']
];
const files=['ZraUl','Kalha','KalZakath','Barbak','Ogunta','Jaskar','GulRak'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dossier(page){const p=new URLSearchParams(location.search), n=Number((p.get('player')||'pj_0').replace('pj_','')); const u=new URL((files[n]||files[0])+'_Dossier_Adepte_V0_33_Connecte.html',location.href);p.delete('role');u.search=p.toString();u.hash=page;return u.href;}
function action(page,label){return page==='market'?'<button class="btn" data-jump="market">'+label+'</button>':'<a class="btn" href="'+esc(dossier(page))+'">'+label+'</a>';}
function render(){
const home=document.getElementById('view-resources');
if(!home.dataset.ready){home.dataset.ready='1';home.innerHTML=`<article class="card green"><span class="tag">Situation jouée • 4 Riag 1448</span><h2 style="margin-top:12px">Au camp des survivants</h2><p>Après la perte du Luxueux, le groupe a rejoint la terre ferme. Keltanap est encore à quelques jours de marche.</p><p class="muted">Repos, route et activités à venir restent à confirmer en jeu. Le marché annoncé représente une prochaine occasion d’achat.</p></article><h2 style="margin-top:24px">Que souhaitez-vous préparer ?</h2><div class="grid three"><article class="card"><h3>Faire évoluer mon personnage</h3><p>Consulter les possibilités, préparer un apprentissage et vérifier les conditions.</p>${action('progression','Ouvrir ma progression')}</article><article class="card"><h3>Organiser mon équipement</h3><p>Vérifier ma charge, puis consulter les biens et services proposés.</p><div class="actions">${action('gear','Mon équipement')}${action('market','Consulter le marché')}</div></article><article class="card"><h3>Proposer un interlude</h3><p>Rechercher un maître, travailler, entretenir une relation ou suivre une piste.</p>${action('notes','Ouvrir mon carnet')}</article></div><article class="card" style="margin-top:18px"><h2>Préparer ma demande d’interlude</h2><p>Un aide-mémoire personnel à reprendre dans <b>Carnet de notes → Interludes</b>. Il ne transmet rien au MJ.</p><label class="field">Mon objectif, le temps, les contacts et le budget<textarea id="interludeDraft" placeholder="Je souhaite… Je prévois… Je m’appuie sur… Mon budget et mon train de vie…"></textarea></label><p id="draftStatus" class="muted" role="status"></p>${action('notes','Aller au carnet pour transmettre')}</article><div class="notice" style="margin-top:18px">Une intention devient un acquis après validation du MJ. Évitez de déclarer deux fois un achat ou un apprentissage déjà transmis par son outil.</div>`;
const p=new URLSearchParams(location.search),key='vorkana-interlude-preparation-v1:'+ (p.get('room')||'default')+':'+(p.get('player')||'pj_0'),field=document.getElementById('interludeDraft'),status=document.getElementById('draftStatus');
try{field.value=localStorage.getItem(key)||'';status.textContent='Brouillon conservé dans ce navigateur, pour ce personnage et cette salle.';}catch{status.textContent='Stockage indisponible : copiez votre texte avant de quitter.';}
field.addEventListener('input',()=>{try{localStorage.setItem(key,field.value);status.textContent='Brouillon enregistré dans ce navigateur. Non transmis.';}catch{status.textContent='Enregistrement impossible : copiez votre texte avant de quitter.';}});
home.addEventListener('click',jump);
}
const aids=document.getElementById('view-aides');if(aids.dataset.ready)return;aids.dataset.ready='1';
aids.innerHTML='<article class="card"><h2>Retrouver une aide</h2><p>Repères pratiques adaptés aux décisions de notre table.</p><label class="field">Rechercher une règle ou une activité<input id="aidSearch" type="search" placeholder="Interlude, blessure, achat, Force…"></label><p id="aidCount" class="muted" role="status"></p><div id="aidResults" class="grid two"></div></article><p class="muted">Sources : règles de table consolidées et aide Interludes du carnet GPT vision. Les autres pages OneNote seront ajoutées après lecture et vérification ; elles ne sont pas encore reproduites ici.</p>';
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function filter(){const q=normalize(document.getElementById('aidSearch').value), found=guides.filter(g=>normalize(g.join(' ')).includes(q));document.getElementById('aidCount').textContent=found.length+' aide(s) trouvée(s)';document.getElementById('aidResults').innerHTML=found.length?found.map(([cat,title,body,target])=>'<article class="card"><span class="tag">'+esc(cat)+'</span><h3 style="margin-top:12px">'+esc(title)+'</h3><p>'+esc(body)+'</p>'+action(target,target==='market'?'Ouvrir le marché':'Ouvrir ma fiche')+'</article>').join(''):'<p>Aucune aide correspondante. Essayez un autre mot.</p>';}
document.getElementById('aidSearch').addEventListener('input',filter);aids.addEventListener('click',jump);filter();
}
function jump(e){const b=e.target.closest('[data-jump]');if(b){document.querySelector('#tabs [data-view="'+b.dataset.jump+'"]').click();scrollTo(0,0);}}
window.VorkanaAides={render};
})();
