/* Aides publiques : synthèse du maître 06 et de l'aide Interludes de GPT vision. */
(()=>{'use strict';
const guides=[
['Interludes','Préparer une activité entre deux aventures','Annoncez un objectif, le temps souhaité, le lieu ou le contact, les moyens et le budget. Le MJ confirme le temps réellement disponible et le résultat. Une activité ordinaire, accessible et financée ne demande pas systématiquement de jet. Une rareté, une opposition ou un délai peuvent créer une incertitude.','notes'],
['Progression','Apprendre et préparer un passage de Cercle','Utilisez Progression pour préparer talents, compétences et attributs, puis vérifier les coûts et conditions. Chercher un mentor peut faire l’objet d’un interlude. Le passage de Cercle reste un événement joué : une préparation ne le valide pas automatiquement.','progression'],
['Commerce','Acheter ou vendre sans double déclaration','Consultez les disponibilités du marché, puis transmettez votre proposition dans Biens & services. Une proposition ne modifie pas à elle seule l’argent ou l’inventaire. L’accord laisse une alerte au MJ : il intègre les conséquences au dossier maître, puis publie la fiche corrigée. Inutile de recopier le même achat dans un interlude ; vous pouvez y ajouter la recherche d’un artisan ou une négociation particulière.','market'],
['Équipement','Transporter, soulever et s’encombrer','La capacité de transport indique le poids porté sans malus. La capacité à soulever est distincte : elle ne permet pas de marcher avec cette charge. Au-delà du transport, la Dextérité diminue de l’écart entre la Force minimale nécessaire et la Force réelle. Exemple : FOR 13 = 55 kg à transporter et 110 kg à soulever. Le calculateur du marché permet de préparer une charge.','gear'],
['Règles de table','Bonus, blessures et récupération','Un modificateur numérique de test modifie le niveau avant le lancer, avec un minimum de 1. Les dés de Karma s’ajoutent séparément. La première Blessure grave ne pénalise pas les tests d’action ; chaque suivante impose −1 niveau. Pour un test de récupération, chaque Blessure grave impose −1 niveau.','combat'],
['Interludes','Choisir son train de vie','Modeste : économies et confort limité. Convenable : conditions ordinaires. Confortable : bon repos et dépenses visibles. Fastueux : prestige et accès à certains milieux, mais aussi attention accrue. Ces choix ont des conséquences économiques et sociales, sans pénalité automatique sur les talents. Indiquez votre choix et votre budget dans la demande.','notes'],
['Magie et groupe','Rechercher un objet ou développer les liens du groupe','Un interlude peut servir à retrouver un Nom, un témoin, une archive ou une légende. Un objet Nommé n’est pas automatiquement magique ou à filament. Une recherche ne révèle pas automatiquement une connaissance-clef et ne dépense pas de PL à elle seule. Les liens du groupe se développent dans le récit ; aucun avantage avancé de trame de groupe n’est accordé automatiquement.','notes']
];
guides.push(...(window.VorkanaAidesContenu||[]));
const files=['ZraUl','Kalha','KalZakath','Barbak','Ogunta','Jaskar','GulRak'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function action(page,label){return page==='market'?'<button class="btn" data-jump="market">'+label+'</button>':window.VorkanaHub.sheetLink(page,label);}
function render(){
const home=document.getElementById('view-resources');
if(!home.dataset.ready){home.dataset.ready='1';const r=window.VorkanaReperes;
home.innerHTML='<article class="card green"><span class="tag">Point de reprise</span><h2 style="margin-top:12px">'+esc(r.location)+'</h2><p><b>'+esc(r.date)+'</b></p><p>'+esc(r.summary)+'</p></article><h2 style="margin-top:24px">Que souhaitez-vous faire ?</h2><div class="grid three"><article class="card"><h3>Acheter ou vendre</h3><p>Consulter les offres, préciser votre demande et suivre son intégration au dossier.</p>'+action('market','Consulter les offres')+'</article><article class="card"><h3>Retrouver une personne</h3><p>Visages, noms et récits associés aux rencontres de Vorkana.</p><button class="btn" data-open-view="entourage">Parcourir les personnes</button></article><article class="card"><h3>Me repérer dans le temps</h3><p>Faits joués, point de reprise et prévisions sont distingués.</p><button class="btn" data-open-view="calendar">Ouvrir la chronologie</button></article><article class="card"><h3>Faire évoluer mon personnage</h3><p>Préparer un apprentissage et vérifier ses conditions.</p>'+action('progression','Ma progression')+'</article><article class="card"><h3>Organiser mon équipement</h3><p>Vérifier ce que je transporte.</p>'+action('gear','Mon équipement')+'</article><article class="card"><h3>Préparer une activité</h3><p>'+esc(r.interlude)+'</p>'+action('notes','Ouvrir mes interludes')+'</article></div><article class="card" style="margin-top:16px"><h2>Récits, lieux et souvenirs</h2><p>Retrouvez un lieu, un souvenir ou une piste dans les récits et les rencontres du groupe.</p><div class="actions"><button class="btn" data-open-view="library">Chercher dans les récits</button><button class="btn" data-open-view="memory">Pistes et souvenirs</button></div></article>';
const p=new URLSearchParams(location.search);if(p.get('role')!=='gm'&&p.get('player')){const key='vorkana-interlude-preparation-v1:'+(p.get('room')||'default')+':'+p.get('player');try{const text=localStorage.getItem(key);if(text){const card=document.createElement('article');card.className='card';card.style.marginTop='16px';card.innerHTML='<h2>Votre ancien brouillon d’interlude</h2><p>Ce texte reste conservé. Reprenez-le dans votre carnet pour le transmettre.</p><textarea readonly aria-label="Ancien brouillon"></textarea>'+action('notes','Ouvrir mon carnet');card.querySelector('textarea').value=text;home.append(card);}}catch{}}
home.addEventListener('click',jump);
}
const aids=document.getElementById('view-aides');if(aids.dataset.ready)return;aids.dataset.ready='1';
aids.innerHTML='<article class="card"><h2>Retrouver une aide</h2><p>Repères pratiques adaptés aux décisions de notre table.</p><label class="field">Rechercher une règle ou une activité<input id="aidSearch" type="search" placeholder="Interlude, blessure, achat, Force…"></label><div id="aidThemes" class="actions" style="margin-top:14px" aria-label="Thèmes des aides"></div><p id="aidCount" class="muted" role="status"></p><div id="aidResults" class="grid two"></div></article><p class="muted">Sources : règles de table, aides GPT vision transmises par le MJ et Recueil du joueur (commerce, p. 432–434). Les règles particulières en attente d’arbitrage sont signalées dans leur aide.</p>';
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const groups={'Interludes':'Entre les aventures','Progression':'Entre les aventures','Commerce':'Commerce et équipement','Équipement':'Commerce et équipement','Règles de table':'Règles et soins','Groupe et récits':'Groupe et légende','Magie et groupe':'Groupe et légende','Magie des sorts':'Magie','Magie de Vie':'Magie','Charmes de sang':'Magie','Passions':'Barsaive et Passions','Histoire de Barsaive':'Barsaive et Passions'};
const prefsKey='vorkana-aides-lecture:'+location.search;let theme='Tous';try{const saved=JSON.parse(sessionStorage.getItem(prefsKey)||'{}');theme=saved.theme||'Tous';document.getElementById('aidSearch').value=saved.search||'';}catch{}
const themes=['Tous',...new Set(Object.values(groups))];if(!themes.includes(theme))theme='Tous';
function themeButtons(){document.getElementById('aidThemes').innerHTML=themes.map(t=>'<button type="button" class="btn" data-theme="'+esc(t)+'" aria-pressed="'+(theme===t)+'" style="'+(theme===t?'border-color:var(--gold);background:#356a47':'')+'">'+esc(t)+' <small>('+guides.filter(g=>t==='Tous'||groups[g[0]]===t).length+')</small></button>').join('');}
document.getElementById('aidThemes').addEventListener('click',e=>{const b=e.target.closest('[data-theme]');if(b){theme=b.dataset.theme;themeButtons();filter();}});themeButtons();
function filter(){try{sessionStorage.setItem(prefsKey,JSON.stringify({theme,search:document.getElementById('aidSearch').value}));}catch{} const q=normalize(document.getElementById('aidSearch').value), found=guides.filter(g=>(theme==='Tous'||groups[g[0]]===theme)&&normalize(JSON.stringify(g)).includes(q));document.getElementById('aidCount').textContent=found.length+' aide(s) trouvée(s)';document.getElementById('aidResults').innerHTML=found.length?found.map(([cat,title,body,target,table])=>'<article class="card"><span class="tag">'+esc(cat)+'</span><h3 style="margin-top:12px">'+esc(title)+'</h3><details><summary>Lire cette aide</summary><p style="white-space:pre-line">'+esc(body)+'</p>'+(table?'<p class="muted">Sur petit écran, faites défiler le tableau horizontalement.</p><div class="table-wrap" tabindex="0" role="region" aria-label="Tableau de référence"><table><thead><tr>'+table.headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+table.rows.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'')+'</details>'+action(target,({market:'Ouvrir le marché',progression:'Ma progression',gear:'Mon équipement',combat:'Mes actions et soins',notes:'Mon carnet'})[target]||'Mon dossier')+'</article>').join(''):'<p>Aucune aide dans ce thème. Essayez un autre mot ou choisissez « Tous ».</p>';}
document.getElementById('aidSearch').addEventListener('input',filter);aids.addEventListener('click',jump);filter();
}
function jump(e){const b=e.target.closest('[data-jump]');if(b){window.VorkanaHub.showView(b.dataset.jump);}}
window.VorkanaAides={render};
})();

