/* Espace commun : règles, vie du personnage, suivi personnel. */
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names=['Zra’Ul','Kalha','Kal’Zakath','Barbak','Ogunta','Jaskar','Gul’Rak'],files=['ZraUl','Kalha','KalZakath','Barbak','Ogunta','Jaskar','GulRak'];
const stores=['earthdawn_player_zraul_v0_2_dossier',...['kalha','kalzakath','barbak','ogunta','jaskar','gulrak'].map(n=>'earthdawn_player_'+n+'_reference_v034')];
const params=new URLSearchParams(location.search),gm=params.get('role')==='gm',preview=gm&&params.has('preview'),playerId=/^pj_[0-6]$/.test(params.get(preview?'preview':'player')||'')?params.get(preview?'preview':'player'):'';
const playerIndex=playerId?Number(playerId.slice(3)):-1,Sync=window.EarthdawnSync,Campaign=window.VorkanaCampaign,R=window.VorkanaReperes,REV=Campaign.fresh().revision;
const room=()=>Sync.status().room,key=()=>`vorkana_circle_player_${room()}_${playerId||'visitor'}_v1`,draftKey=()=>`vorkana_market_draft_${room()}_${playerId}_v1`;
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback;}catch{return fallback;}}
function load(){const value=read(key(),null)||read(`vorkana_circle_${room()}_v033`,null),s=Campaign.migrate(value);s.proposals=s.proposals.filter(p=>p.playerId===playerId);return s;}
let state=load(),draft=playerId&&!gm?read(draftKey(),{}):{},filterText='',filterCategory='',view='',availabilityDirty=false,availabilityRevision=0;
function message(text,error=false){$('hubStatus').textContent=text;$('hubStatus').classList.toggle('error',error);}
function save(){if(gm)return true;try{localStorage.setItem(key(),JSON.stringify(state));return true;}catch{message('Sauvegarde impossible sur cet appareil. Gardez cette page ouverte et réessayez.',true);return false;}}
function sheet(page){const u=new URL((/\/Poste_MJ\//i.test(location.pathname)?'../Site_Joueurs/':'')+(files[playerIndex]||'index')+(playerIndex>=0?'_Dossier_Adepte.html':'.html'),location.href);u.searchParams.set('room',room());if(playerId)u.searchParams.set('player',playerId);u.hash=page||'';return u.href;}
function sheetLink(page,label){return gm?'<span class="muted">'+esc(label)+' : depuis le dossier du joueur</span>':'<a class="btn" href="'+esc(sheet(page))+'">'+esc(playerId?label:'Choisir mon personnage')+'</a>';}
function flag(p){if(p.status==='accepted')return p.integrationStatus==='published'?'Dossier publié':p.integrationStatus==='legacy_review'?'Ancien accord — à rapprocher':'À intégrer au dossier maître';return {pending:'Envoi en attente de réception',received:'Reçue par le MJ',rejected:'Refusée',needs_review:'Ancien marché — à reformuler'}[p.status]||'À examiner';}
function marketCard(p){return `<article class="proposal ${esc(p.status)}"><div><h3>${esc(p.kind)} — ${esc(p.itemName||'Offre libre')}</h3><p class="request-meta">${esc(p.playerName)} · quantité ${esc(p.quantity)} · ${esc(p.price||'Prix à préciser')}</p>${p.note?'<p>'+esc(p.note)+'</p>':''}<span class="state">${esc(flag(p))}</span>${p.status==='accepted'?'<p class="request-meta">'+(p.integrationStatus==='published'?'Publication confirmée par le MJ : '+esc(p.publicationReference||''):'L’accord ne débite pas votre argent et ne modifie pas votre inventaire. Le MJ doit modifier le dossier maître et le transférer.')+'</p>':''}</div></article>`;}
function localRequests(){if(!playerId||gm)return {proposals:[],progressionLedger:{}};return read(stores[playerIndex],{proposals:[],progressionLedger:{}});}
function renderRequests(){
 const host=$('view-requests');if(gm){host.innerHTML=preview?'<article class="card"><h2>Mes demandes</h2><p>Dans son espace, le joueur retrouve ici ses achats, sa progression et ses interludes. Ses brouillons personnels ne sont pas chargés dans cet aperçu.</p></article>':`<article class="card"><h2>À intégrer aux dossiers maîtres</h2><p>Les accords restent ici jusqu’à votre confirmation du dossier modifié et transféré.</p><p>Utilisez la file « À intégrer » du cockpit pour exporter la liste et confirmer chaque publication.</p><div class="request-list">${state.proposals.filter(p=>p.status==='accepted'&&p.integrationStatus!=='published').map(marketCard).join('')||'<p>Aucun accord commercial à intégrer.</p>'}</div></article>`;return;}
 if(!playerId){host.innerHTML='<article class="card"><h2>Mes demandes</h2><p>Choisissez votre personnage pour retrouver vos demandes personnelles.</p>'+sheetLink('','Ouvrir mon dossier')+'</article>';return;}
 const local=localRequests(),personal=(local.proposals||[]).filter(p=>['progression','interlude'].includes(p.kind));
 const mine=state.proposals.filter(p=>p.playerId===playerId),pending=mine.filter(p=>p.status==='accepted'&&p.integrationStatus!=='published').length;
 const draftText=Object.values(draft).some(Boolean)?'<p>Un brouillon commercial vous attend dans <button class="btn small" data-open-view="market">Acheter et vendre</button>.</p>':'';
 host.innerHTML=`<article class="card"><h2>Mes demandes</h2><p>Vos achats, votre progression et vos interludes, sans double déclaration.</p><button class="btn" data-refresh-requests>Actualiser le suivi et réessayer les envois</button><div class="hub-summary"><span>${mine.filter(p=>['pending','received'].includes(p.status)).length} achat(s) en attente</span><span>${pending} accord(s) à intégrer ou rapprocher</span></div>${draftText}<h3>Achats et ventes</h3><div class="request-list">${mine.slice().reverse().map(marketCard).join('')||'<p>Aucune demande commerciale.</p>'}</div></article><article class="card" style="margin-top:16px"><h2>Progression et interludes</h2><p class="muted">Demandes du dossier conservé sur cet appareil. Ouvrez votre dossier pour actualiser les réponses du MJ et poursuivre un brouillon.</p><div class="actions">${sheetLink('progression','Ma progression')}${sheetLink('notes','Mes interludes')}</div><div class="request-list" style="margin-top:14px">${personal.slice().reverse().map(p=>{
 const applied=(local.progressionLedger?.appliedProposalIds||[]).includes(p.id),label=applied?'Intégrée dans la fiche':p.status==='approved'?(p.kind==='interlude'?'Réponse du MJ reçue':'Accord MJ — à intégrer'):({draft:'Brouillon',sent:'Transmise au MJ',rejected:'À revoir avec le MJ'}[p.status]||'À examiner');
 return '<article class="card"><span class="tag">'+(p.kind==='interlude'?'Interlude':'Progression')+'</span><h3>'+esc(p.label||p.kind)+'</h3><p>'+esc(label)+'</p>'+sheetLink(p.kind==='interlude'?'notes':'progression','Voir dans mon dossier')+'</article>';
 }).join('')||'<p>Aucune demande de progression ou d’interlude retrouvée sur cet appareil.</p>'}</div></article>`;
}
function renderCalendar(){
 const previous=[['18 Sollus 1448','Voyage vers Throal et premiers échanges avec la Grande Bibliothèque.'],['19–20 Sollus','Préparatifs à Grand-Foire.'],['21–28 Sollus','Voyage vers Rocnoir, arrivée le 28 au soir.'],['29–30 Sollus','Enquête puis sauvetage de Katsika.']];
 const annual=new URL('Calendrier_Vorkana.html',location.href);annual.search=location.search;
 $('view-calendar').innerHTML='<article class="card"><h2>Chronologie</h2><p class="notice">'+esc(R.date)+' · '+esc(R.location)+'. Arrivée à Keltanap prévue à midi.</p><a class="btn" href="'+esc(annual.href)+'">Voir le calendrier annuel</a><div class="timeline" style="margin-top:20px">'+previous.map(([d,t])=>'<article><b>'+esc(d)+'</b><p>'+esc(t)+'</p></article>').join('')+R.events.map(e=>'<article><span class="tag">'+({played:'Joué',current:'Point de reprise',planned:'Prévu'}[e.status])+'</span><h3>'+e.d+' Riag 1448 — '+esc(e.label)+'</h3><p>'+esc(e.text)+'</p></article>').join('')+'</div></article>';
}
const availabilityLabels={available:'Disponible',limited:'Limité / sur commande',unavailable:'Indisponible',unknown:'À confirmer'};
function catalogRows(items){return items.map(item=>`<tr><td><b>${esc(item.name)}</b><br><small>${esc(item.category)}</small></td><td data-label="Disponibilité">${esc(availabilityLabels[item.status])}${item.stock!==null?' · stock '+esc(item.stock):''}</td><td data-label="Prix">${esc(item.price||'À préciser')}</td><td data-label="Précision">${esc(item.note||'')}</td><td>${!gm&&playerId?`<button class="btn small" data-item="${esc(item.id)}">${state.context.archived?'Demander confirmation':'Préparer une demande'}</button>`:''}</td></tr>`).join('');}
function updateCharge(){const ref=Campaign.reference(),strength=Math.max(1,Math.min(50,Math.trunc(Number($('encStrength').value)||1))),weight=Math.max(0,Number($('encWeight').value)||0),row=ref.carrying.find(r=>r.strength===strength),required=ref.carrying.find(r=>r.carry>=weight);$('encResult').textContent=`FOR ${strength} : ${row.carry} kg sans malus ; ${row.lift} kg à soulever. `+(weight>row.carry?(required?'DEX −'+(required.strength-strength)+' tant que la charge est portée.':'Charge au-delà de la table : arbitrage MJ.'):'Aucun malus d’encombrement.');}
function renderMarket(){
 const active=document.activeElement,focusId=active?.id,start=active?.selectionStart,end=active?.selectionEnd,ref=Campaign.reference();
 const rows=state.catalog.filter(i=>(!filterCategory||i.category===filterCategory)&&fold(i.name+' '+i.note).includes(fold(filterText)));
 $('view-market').innerHTML=`<article class="card"><h2>Acheter et vendre</h2><p><b>${esc(state.context.location)}</b> · ${esc(state.context.date)}</p><p>${esc(state.context.note)}</p>${state.context.archived?'<p class="notice">Ancien marché : les offres sont des repères à faire confirmer. Aucune disponibilité à Keltanap n’est supposée acquise.</p>':''}<div class="grid two"><label class="field">Rechercher<input id="marketSearch" type="search" value="${esc(filterText)}" placeholder="Objet ou service"></label><label class="field">Catégorie<select id="marketCategory"><option value="">Toutes</option>${[...new Set(state.catalog.map(i=>i.category))].map(c=>'<option '+(filterCategory===c?'selected':'')+'>'+esc(c)+'</option>').join('')}</select></label></div><div class="table-wrap"><table class="market-table"><thead><tr><th>Offre</th><th>Disponibilité</th><th>Prix</th><th>Précision</th><th>Action</th></tr></thead><tbody id="marketRows">${catalogRows(rows)}</tbody></table></div></article>
 ${!gm&&playerId?`<article class="card" style="margin-top:16px" id="proposalForm"><h2>Préparer ma demande</h2><div class="grid two"><label class="field">Opération<select id="proposalKind"><option>Achat</option><option>Vente</option></select></label><label class="field">Article<select id="proposalItem"><option value="custom">Autre / offre personnelle</option>${state.catalog.map(i=>'<option value="'+esc(i.id)+'">'+esc(i.name)+'</option>').join('')}</select></label><label class="field">Quantité<input id="proposalQty" type="number" min="1" max="10000" step="1" value="1"></label><label class="field">Prix proposé et monnaie<input id="proposalPrice" maxlength="250" placeholder="Ex. 12 PA au total, à confirmer"></label><label class="field wide">Détail et conditions<textarea id="proposalNote" maxlength="6000" placeholder="Objet exact, état, délai, négociation souhaitée…"></textarea></label></div><p class="muted">Indiquez si le prix est unitaire ou total. Un changement de conditions doit recevoir votre accord. L’argent et l’inventaire seront intégrés par le MJ dans le dossier maître, puis publiés.</p><button class="btn primary" id="sendProposal">Transmettre au MJ</button> <button class="btn" data-open-view="requests">Suivre mes demandes</button><p id="marketDraftStatus" role="status"></p></article>`:!gm?'<article class="card" style="margin-top:16px"><p>Choisissez votre personnage pour préparer un achat.</p>'+sheetLink('','Mon dossier')+'</article>':''}
 <details class="card" style="margin-top:16px"><summary>Références d’équipement et calcul d’encombrement</summary><p>Ces références n’établissent pas la disponibilité sur ce marché.</p><div class="table-wrap"><table><thead><tr><th>Objet</th><th>Prix</th><th>Poids</th><th>Précision</th></tr></thead><tbody>${ref.equipment.map(i=>'<tr><td>'+esc(i.name)+'</td><td>'+esc(i.price)+'</td><td>'+esc(i.weight)+'</td><td>'+esc(i.note)+'</td></tr>').join('')}</tbody></table></div><div class="grid two"><label class="field">Force<input id="encStrength" type="number" min="1" max="50" value="10"></label><label class="field">Charge portée (kg)<input id="encWeight" type="number" min="0" step="0.05" value="0"></label></div><p id="encResult" role="status"></p><p>${esc(ref.rules.lifting)} En vol, un sylphelin divise sa capacité de transport par deux.</p><details><summary>Table complète des capacités</summary><div class="table-wrap"><table><thead><tr><th>FOR</th><th>Transport (kg)</th><th>Soulèvement (kg)</th></tr></thead><tbody>${ref.carrying.map(r=>'<tr><td>'+r.strength+'</td><td>'+r.carry+'</td><td>'+r.lift+'</td></tr>').join('')}</tbody></table></div></details></details>`;
 $('marketSearch').oninput=e=>{filterText=e.target.value;filterMarket();};$('marketCategory').onchange=e=>{filterCategory=e.target.value;filterMarket();};
 $('encStrength').oninput=updateCharge;$('encWeight').oninput=updateCharge;updateCharge();
 if($('proposalForm')){
  for(const id of ['proposalKind','proposalItem','proposalQty','proposalPrice','proposalNote']){if(draft[id]!==undefined)$(id).value=draft[id];$(id).addEventListener('input',rememberDraft);$(id).addEventListener('change',rememberDraft);}
  $('sendProposal').onclick=sendProposal;$('marketDraftStatus').textContent='Brouillon conservé sur cet appareil. Non transmis.';
 }
 if(focusId&&$(focusId)){const el=$(focusId);el.focus({preventScroll:true});if(typeof start==='number'&&el.setSelectionRange)try{el.setSelectionRange(start,end);}catch{}}
}
function fold(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function filterMarket(){$('marketRows').innerHTML=catalogRows(state.catalog.filter(i=>(!filterCategory||i.category===filterCategory)&&fold(i.name+' '+i.note).includes(fold(filterText))));}
function rememberDraft(){for(const id of ['proposalKind','proposalItem','proposalQty','proposalPrice','proposalNote'])draft[id]=$(id)?.value||'';try{localStorage.setItem(draftKey(),JSON.stringify(draft));$('marketDraftStatus').textContent='Brouillon enregistré. Non transmis.';}catch{$('marketDraftStatus').textContent='Enregistrement impossible : copiez votre texte avant de quitter.';}}
let sending=false;
function sendProposal(){
 if(gm||!playerId||sending)return;const quantity=Number($('proposalQty').value);if(!Number.isInteger(quantity)||quantity<1||quantity>10000){message('La quantité doit être un nombre entier de 1 à 10 000.',true);$('proposalQty').focus();return;}
 const item=state.catalog.find(i=>i.id===$('proposalItem').value),note=$('proposalNote').value.trim();if(!item&&!note){message('Précisez l’objet ou le service de votre offre personnelle.',true);$('proposalNote').focus();return;}
 const proposal={id:'market-'+Date.now()+'-'+Math.random().toString(36).slice(2),marketRevision:REV,playerId,playerName:names[playerIndex],kind:$('proposalKind').value,itemId:item?.id||'',itemName:item?.name||'Offre personnelle',quantity,price:$('proposalPrice').value.trim(),note,status:'pending',sentAt:new Date().toISOString()};
 sending=true;$('sendProposal').disabled=true;state.proposals.push(proposal);
 if(!save()){state.proposals.pop();sending=false;$('sendProposal').disabled=false;return;}
 draft={};try{localStorage.removeItem(draftKey());}catch{}
 try{Sync.sendToGM({type:'vorkana-market-proposal',proposal});message('Demande conservée. Elle restera en attente jusqu’à sa réception par le MJ.');}catch{message('Demande conservée : envoi à réessayer depuis Mes demandes.',true);}
 renderMarket();renderRequests();showView('requests');setTimeout(()=>{sending=false;},500);
}
function renderAvailability(){
 if(!gm||preview||availabilityDirty)return;availabilityRevision=state.revisionNumber||0;
 $('view-availability').innerHTML=`<article class="card"><h2>Disponibilités MJ</h2><p>Ces informations sont diffusées à la salle par le cockpit. Elles ne modifient pas les dossiers maîtres.</p><div class="grid two"><label class="field">Date du marché<input id="contextDate" value="${esc(state.context.date)}"></label><label class="field">Lieu du marché<input id="contextLocation" value="${esc(state.context.location)}"></label><label class="field wide">Note publique<textarea id="contextNote">${esc(state.context.note)}</textarea></label></div><label><input type="checkbox" id="marketArchived" ${state.context.archived?'checked':''}> Marché archivé : disponibilités à reconfirmer avant accord</label><p>Pour ouvrir un marché, vérifiez lieu, prix et disponibilités puis décochez cette case.</p><div class="table-wrap"><table><thead><tr><th>Offre</th><th>État</th><th>Stock</th><th>Prix</th><th>Note</th></tr></thead><tbody>${state.catalog.map(i=>`<tr><td>${esc(i.name)}</td><td><select aria-label="Disponibilité ${esc(i.name)}" data-status="${esc(i.id)}">${Object.entries(availabilityLabels).map(([v,l])=>'<option value="'+v+'" '+(i.status===v?'selected':'')+'>'+esc(l)+'</option>').join('')}</select></td><td><input aria-label="Stock ${esc(i.name)}" type="number" min="0" step="1" data-stock="${esc(i.id)}" value="${i.stock===null?'':i.stock}"></td><td><input aria-label="Prix ${esc(i.name)}" data-price="${esc(i.id)}" value="${esc(i.price)}"></td><td><input aria-label="Note ${esc(i.name)}" data-note="${esc(i.id)}" value="${esc(i.note)}"></td></tr>`).join('')}</tbody></table></div><div class="actions"><button id="publishCatalog" class="btn primary">Transmettre le marché au cockpit</button><button id="reloadAvailability" class="btn">Recharger les valeurs confirmées</button></div></article>`;
 $('view-availability').oninput=()=>{availabilityDirty=true;};
 $('reloadAvailability').onclick=()=>{if(availabilityDirty&&!confirm('Abandonner les modifications du marché non transmises ?'))return;availabilityDirty=false;renderAvailability();};
 $('publishCatalog').onclick=()=>{
  const context={date:$('contextDate').value.trim(),location:$('contextLocation').value.trim(),note:$('contextNote').value.trim(),archived:$('marketArchived').checked};
  const catalog=state.catalog.map(i=>{const q=s=>$('view-availability').querySelector(`[data-${s}="${i.id}"]`),raw=q('stock').value;return {...i,status:q('status').value,stock:raw===''?null:Number(raw),price:q('price').value.trim(),note:q('note').value.trim()};});
  if(!context.location||!context.date||catalog.some(i=>i.stock!==null&&(!Number.isInteger(i.stock)||i.stock<0))){message('Vérifiez le lieu, la date et les stocks entiers positifs ou nuls.',true);return;}
  try{Campaign.publish(context,catalog,availabilityRevision);availabilityDirty=false;message('Marché transmis. Attente de confirmation par le cockpit.');}catch(e){message(e.message,true);}
 };
}
const publicViews=['resources','aides','market','entourage','library','memory','calendar','requests'];
function showView(next,historyMode='push'){
 if(!publicViews.includes(next)&&!(gm&&!preview&&next==='availability'))next='resources';view=next;
 document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id==='view-'+next));
 const group=next==='aides'?'aides':next==='requests'?'requests':'resources';
 document.querySelectorAll('[data-primary]').forEach(b=>{if(b.dataset.primary===group)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
 document.querySelectorAll('#tabs [data-view]').forEach(b=>{b.hidden=(next==='aides'||next==='requests')&&b.dataset.view!=='availability'||b.dataset.view==='availability'&&(!gm||preview);if(b.dataset.view===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
 if(next==='requests')renderRequests();
 if(historyMode!=='none'&&location.hash!=='#'+next){const u=new URL(location);u.hash=next;u.searchParams.delete('document');history[historyMode==='replace'?'replaceState':'pushState'](null,'',u);}
 if(historyMode==='push'){const h=$('view-'+next)?.querySelector('h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo(0,0);}
}
document.addEventListener('click',e=>{
 if(e.target.closest('[data-refresh-requests]')){resend();renderRequests();message('Actualisation demandée. Les envois en attente conservent leur identifiant.');return;}
 const open=e.target.closest('[data-primary],[data-open-view],#tabs [data-view]');if(open){showView(open.dataset.primary||open.dataset.openView||open.dataset.view);return;}
 const item=e.target.closest('[data-item]');if(item&&$('proposalItem')){$('proposalItem').value=item.dataset.item;rememberDraft();$('proposalQty').focus();$('proposalForm').scrollIntoView({block:'start'});}
});
window.addEventListener('popstate',()=>showView(location.hash.slice(1),'none'));window.addEventListener('hashchange',()=>showView(location.hash.slice(1),'none'));
function render(){window.VorkanaAides.render();renderCalendar();renderMarket();renderAvailability();renderRequests();}
function resend(){if(!gm&&playerId){Sync.sendToGM({type:'vorkana-hub-request',playerId});state.proposals.filter(p=>p.status==='pending').forEach(proposal=>Sync.sendToGM({type:'vorkana-market-proposal',proposal}));}}
Sync.configure({role:gm?'gm':'player',playerId:gm?'':playerId,name:gm?'MJ':names[playerIndex]||'Visiteur'}).start();
if(gm){Campaign.start(false);state=JSON.parse(JSON.stringify(Campaign.state()));}
$('hubIdentity').textContent=gm?(preview?'Aperçu joueur : '+(names[playerIndex]||'vue générale'):'Vue MJ — espace commun'):(playerId?'Personnage : '+names[playerIndex]:'Consultation des aides · choisissez un personnage pour vos demandes');
$('campaignNow').textContent=R.date+' · '+R.location;
if(gm){$('previewTools').hidden=false;$('previewPlayer').innerHTML=names.map((n,i)=>'<option value="pj_'+i+'" '+(playerId==='pj_'+i?'selected':'')+'>'+esc(n)+'</option>').join('');$('previewButton').onclick=()=>{const u=new URL(location);u.searchParams.set('preview',$('previewPlayer').value);location.href=u.href;};$('previewExit').hidden=!preview;$('previewExit').onclick=()=>{const u=new URL(location);u.searchParams.delete('preview');location.href=u.href;};}
window.addEventListener('vorkana-campaign-changed',()=>{if(!gm)return;state=JSON.parse(JSON.stringify(Campaign.state()));renderMarket();renderAvailability();renderRequests();message('État confirmé par le cockpit.');});
window.addEventListener('vorkana-campaign-error',e=>message(e.detail.message,true));
window.addEventListener('earthdawn-sync-status',e=>{const online=e.detail.status==='online';$('syncStatus').classList.toggle('online',online);$('syncStatus').querySelector('span').textContent=(online?'En ligne':'Mode local')+' · salle '+e.detail.room;if(online){if(gm)Sync.sendToGM({type:'vorkana-hub-request',asGM:true});else resend();}});
window.addEventListener('earthdawn-sync-message',e=>{
 if(gm)return;const d=e.detail.payload||{};
 if(d.type==='vorkana-hub-state'&&d.state?.revision===REV&&Number(d.state.revisionNumber||0)>=Number(state.revisionNumber||0)){for(const k of ['context','catalog','revisionNumber','updatedAt'])if(d.state[k]!==undefined)state[k]=d.state[k];save();renderMarket();renderRequests();}
 else if(d.type==='vorkana-market-decision'){
  let p=state.proposals.find(p=>p.id===d.proposalId&&p.playerId===playerId);if(!p&&d.proposal?.playerId===playerId){p={...d.proposal};state.proposals.push(p);}
  if(!p||Number(d.proposalVersion||0)<Number(p.proposalVersion||0)||(['accepted','rejected'].includes(p.status)&&!['accepted','rejected'].includes(d.status)))return;
  if(d.proposal?.playerId===playerId)Object.assign(p,d.proposal);else Object.assign(p,{status:d.status,decidedAt:d.decidedAt});save();renderRequests();
 }
});
window.addEventListener('storage',e=>{if(stores.includes(e.key))renderRequests();});
window.addEventListener('focus',()=>{renderRequests();resend();});
window.addEventListener('beforeunload',e=>{if(availabilityDirty){e.preventDefault();e.returnValue='';}});
window.VorkanaHub={showView,renderRequests,sheetLink,flag,resend};
render();showView(location.hash.slice(1)||'resources','replace');const connection=Sync.status();$('syncStatus').classList.toggle('online',connection.status==='online');$('syncStatus').querySelector('span').textContent=(connection.status==='online'?'En ligne':'Mode local')+' · salle '+connection.room;resend();
})();
