(()=>{'use strict';
const entries=[
['Personnes','Koldar','Grand-Foire','Contact connu','Maître de Barbak. Il a organisé la célébration de la naissance de Vorkana. Un interlocuteur pour parler de formation et du sens des actes du groupe.','Barbak, groupe','17 Naissance de Vorkana ; continuité consolidée'],
['Personnes','Ysillia « Danse entre les cendres »','Grand-Foire','Rencontre vécue','Sylpheline et élève de Koldar, surnommée l’Aiguille sur sang. Barbak s’est entraîné avec elle ; Jaskar a recueilli une partie de son histoire. Sa disponibilité actuelle reste à vérifier avant de projeter un nouvel entraînement.','Barbak, Jaskar','17 Naissance de Vorkana'],
['Personnes','Elroën Vélaris','Grand-Foire / Throal','Contact connu','Questeur de Mynbruje rencontré à Grand-Foire. Il s’est intéressé au choix d’Ogunta d’avertir le messager menacé. D’après le récit, il possède une demeure à Throal près de la Grande Bibliothèque : un lieu où chercher à le retrouver, sans rendez-vous déjà fixé.','Ogunta, Kal’Zakath','17 Naissance de Vorkana'],
['Personnes','Voluptia la Flagellante','L’Insoumise','Mission accomplie','Capitaine de l’Insoumise et lahala de Beaulimon. Le groupe lui a ramené Katsika vivant. La dette de mission est honorée ; cette relation favorable ne vaut pas alliance ni service gratuit automatique.','Groupe','23 Les vieux amants ; issue confirmée dans la continuité'],
['Personnes','Katsika Vif-Acier','Rocnoir / l’Insoumise','Sauvetage terminé','Libéré de l’île des Naufrageurs sans alarme ni combat, puis ramené vivant à Voluptia. Il appartient désormais aux personnes connues du groupe, et non à une liste de prisonniers encore à secourir.','Groupe','23 Les vieux amants ; continuité consolidée'],
['Personnes','Nicodémus','Rocnoir','Contact marchand','Marchand retrouvé pendant la recherche de Katsika. Le groupe lui a acheté un ornement marin pour 24 pa après négociation. Kalha a reconnu un élément de décoration, probablement issu d’un bateau, plutôt qu’un simple bijou.','Gul’Rak, Kalha, groupe','23 Les vieux amants'],
['Personnes','M’rok','Rocnoir','Contact connu','Obsidien qui a renseigné le groupe sur Katsika, la plage des Coques et Yourk. Il a écouté Zra’Ul évoquer Yu’ri et la roche-de-vie. Il a également raconté l’histoire de Barne. Ses récits restent attribués à leur narrateur.','Zra’Ul, Kal’Zakath, groupe','23 Les vieux amants'],
['Pistes','Reprendre contact avec les rencontres de Grand-Foire','Grand-Foire / Throal','Possibilité, pas engagement','Souhaitez-vous retrouver Koldar, Ysillia ou Elroën ? Précisez le but : entraînement, conversation, conseil ou partage d’un récit. Aucun de ces contacts n’est réputé disponible sans vérification.','Groupe','Suggestion de préparation fondée sur le récit 17'],
['Pistes','Les recherches sur Mordom et l’Anneau','Grande Bibliothèque de Throal','Ancienne piste à faire le point','Le récit de la naissance de Vorkana propose une recherche à la Bibliothèque. Avant une nouvelle démarche, rassembler les réponses déjà obtenues et formuler ce qui manque encore. Cette note ne signifie pas que toute la recherche reste à faire.','Groupe','Piste exprimée dans le récit 17 ; statut actuel à préciser avec le MJ'],
['Pistes','L’ornement acheté à Rocnoir','Équipement du groupe','Question pratique','Qui conserve actuellement l’ornement marin acheté chez Nicodémus ? Le porteur n’est pas fixé dans la continuité. Le groupe peut le préciser au MJ pour retrouver facilement cet objet. Cette page ne l’ajoute à aucun inventaire.','Groupe','23 Les vieux amants ; inventaire collectif consolidé'],
['Souvenirs','Vorkana, la Main Rayonnante','Grand-Foire — 28 Mawag 1448','Fait joué','Kalha fabrique les médaillons : une main ork sur un soleil rayonnant. Koldar célèbre la naissance du groupe. Un souvenir fondateur que chacun peut reprendre lorsqu’il raconte ce que représente Vorkana.','Groupe','17 Naissance de Vorkana — récit de Barbak'],
['Souvenirs','Vorkana a fait justice','Rocnoir — nuit du 29 au 30 Sollus 1448','Fait joué','Après le sauvetage de Katsika, Kal’Zakath revendique l’action auprès de la Capitainerie au nom de Vorkana. Le groupe a donné une signature publique à son acte ; les réactions futures ne sont pas encore des faits.','Groupe','23 Les vieux amants — récit de Jaskar ; continuité consolidée'],
['Souvenirs','Le Fleuve garde les Noms','Voyage vers Rocnoir','Souvenir partagé','Les marins chantent en mémoire de Chickao Pluie-de-sang. Jaskar et Zra’Ul retiennent la chanson. Cette fiche rappelle le souvenir ; elle ne reconstitue pas des paroles absentes des récits consultés.','Jaskar, Zra’Ul','23 Les vieux amants — récit de Barbak']
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fold=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const host=document.getElementById('view-memory');if(!host)return;host.innerHTML='<article class="card"><h2>Mémoire du groupe</h2><p>Retrouver une personne, reprendre une question ou se rappeler un moment vécu.</p><p class="muted">Première sélection : naissance de Vorkana et aventure de Rocnoir. Les autres récits restent à intégrer.</p><div class="grid two"><label class="field">Rechercher<input type="search" id="memorySearch" placeholder="Nom, lieu, personnage…"></label><label class="field">Afficher<select id="memoryKind"><option>Tous</option><option>Personnes</option><option>Pistes</option><option>Souvenirs</option></select></label></div><p id="memoryCount" role="status" class="muted"></p><div id="memoryResults" class="grid two"></div></article>';
function render(){const q=fold(document.getElementById('memorySearch').value),kind=document.getElementById('memoryKind').value;const found=entries.filter(e=>(kind==='Tous'||e[0]===kind)&&fold(e.join(' ')).includes(q));document.getElementById('memoryCount').textContent=found.length+' repère(s)';document.getElementById('memoryResults').innerHTML=found.length?found.map(([type,name,place,status,body,people,source])=>'<article class="card"><span class="tag">'+esc(type)+'</span><h3 style="margin:12px 0 6px">'+esc(name)+'</h3><p class="muted">'+esc(place)+'</p><b>'+esc(status)+'</b><p>'+esc(body)+'</p><small class="muted">Personnages concernés : '+esc(people)+'</small><details style="margin-top:12px"><summary>Origine du repère</summary><p>'+esc(source)+'</p></details></article>').join(''):'<p>Aucun repère correspondant. Essayez un autre mot ou une autre rubrique.</p>';}
document.getElementById('memorySearch').addEventListener('input',render);document.getElementById('memoryKind').addEventListener('change',render);render();
})();
